/*
Root Layout 은 각 metadata를 세팅할 수 있는 컴포넌트이다.

The app directory must include a root app/layout.js.
app 디렉토리는 app/layout.js를 무조건 포함하고 있어야 한다.
*/

// import './globals.css'
import { Inter } from 'next/font/google'
// import Link from "next/link";
// import HeaderLayout from "@/2_view/layout/HeaderLayout";
import TestContainer from "@/2_view/layout/TestContainer";
// import {createContext} from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Root layout',
  description: 'Generated by create next app',
}

const getCurrentTheme = (): string => {
  const currentTheme = localStorage.getItem('dark');
  if (currentTheme) {
    return currentTheme
  } else {
    return 'light'
  }
};
// const ThemeProvider = createContext(getCurrentTheme());

export default function RootLayout({children,}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* 각 종 메타데이터 삽입 */}
      <body className={inter.className}>
        {/*<ThemeProvider.Provider value={'light'}>*/}
        <TestContainer /> {/* CSR */}
          {/*<HeaderLayout onClick={() => console.log('asdlkfjs')} /> /!* SSR *!/*/}
          {children}
        {/*</ThemeProvider.Provider>*/}
      </body>
    </html>
  )
}
